### ISSUE TITLE
PAS2GEF errors out when processing small GTF file

### ISSUE THREAD

**Issue by faricazjj** [RJWANGbioinfo/APAlyzer#9] opened 2021-11-17 03:17 UTC
Hi, 

I'm provided a small [Gencode GTF file](https://github.com/iRNA-COSI/APAeval/blob/main/tests/test_data/gencode_2genes_Chr_prefix.vM18.annotation.gtf) with ~500 lines that I'd like to use to obtain reference regions from for APAlyzer. The code I'm using is:
```
GTFfile="Mus_musculus.GRCm38.98.gtf.gz"	
PASREFraw=PAS2GEF(GTFfile)	
refUTRraw=PASREFraw$refUTRraw
dfIPAraw=PASREFraw$dfIPA
dfLEraw=PASREFraw$dfLE
PASREF=REF4PAS(refUTRraw,dfIPAraw,dfLEraw)
```

However, I'm getting the following error:
```
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'flesh' in selecting a method for function 'relist': subscript contains out-of-bounds indices
Calls: PAS2GEF ... normalizeSingleBracketSubscript -> NSBS -> NSBS -> .subscript_error
```

**Comment by RJWANGbioinfo** [comment] 2021-11-20 22:34
@faricazjj thanks for the feedback, I will use this example file to check it

**Comment by RJWANGbioinfo** [comment] 2021-11-28 09:19
@faricazjj , this issue is caused by the conflict between the annotator and GTF format in the previous version.
It has been fixed now in the latest version. You can update your APAlyzer through:
```
BiocManager::install('RJWANGbioinfo/APAlyzer')
```
Then  build the reference through using your GTF file:
```
GTFfile="gencode_2genes_Chr_prefix.vM18.annotation.gtf"
PASREFraw=PAS2GEF(GTFfile, AnnoMethod="V2")  
refUTRraw=PASREFraw$refUTRraw
dfIPAraw=PASREFraw$dfIPA
dfLEraw=PASREFraw$dfLE
PASREF=REF4PAS(refUTRraw,dfIPAraw,dfLEraw)
```

**Comment by RJWANGbioinfo** [comment] 2021-12-01 00:48
close this ticket since it's fixed

**Closed as completed by RJWANGbioinfo** 2021-12-01 00:48 UTC

**Comment by faricazjj** [comment] 2021-12-05 19:56
@RJWANGbioinfo Thank you for the fix! I ran this to reinstall the package
`BiocManager::install('RJWANGbioinfo/APAlyzer')`
But I get the error 
`Error in PAS2GEF(GTFfile, AnnoMethod = "V2") :
  unused argument (AnnoMethod = "V2")`
  I checked that the version I had installed is 1.7.3. Is this correct the version with the new AnnoMethod parameter?

**Comment by faricazjj** [comment] 2021-12-06 05:09
@RJWANGbioinfo Thank you for the fix! I reinstalled APAlyzer and is now version 1.9.1. I then tried running the block of code in your comment above with the same GTF file and I'm faced with this error message:
`Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'i' in selecting a method for function '[': could not find function "queryHits"
Calls: PAS2GEF ... .annotatePAS_V2 -> .annotatePASRegion -> [ -> .handleSimpleError -> h`

Am I missing anything to run this successfully with the new version?

**Comment by faricazjj** [comment] 2021-12-23 23:46
Hi @RJWANGbioinfo! I tried running the code above with AnnoMethod="V2" using APAlyzer version 1.9.1 but obtained the following error
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'i' in selecting a method for function '[': could not find function "queryHits"
In addition: Warning message:
In .get_cds_IDX(mcols0$type, mcols0$phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
```

Have you encountered this error or know how to fix it?
