### ISSUE TITLE
error in APAdiff

### ISSUE THREAD

**Issue by grexor** [RJWANGbioinfo/APAlyzer#8] opened 2021-06-16 11:28 UTC
Running the software on my data, I get this error at the APAdiff step:

```
Error in `$<-.data.frame`(`*tmp*`, APAreg, value = "NC") : 
  replacement has 1 row, data has 0
```

After some debugging, I found out the error is generated in this function:

`.calt_p<-function(dfsubXXX,col9S,col10S,adjust_methods)`

Looks like perhaps some values in the data are NA or missing and this produces an error? Please advise

**Comment by ruijiaqiagen** [comment] 2021-07-10 02:43
Hi @grexor ,
Thanks for your feedback. It seems we can not reproduce this error using either our testing data or internal data.
To help us track the issue, do you mind sharing with us the subset of your data (either rds/txt/tsv should be fine) triggering this error? Thank you.

**Comment by grexor** [comment] 2021-07-12 07:55
Thanks for the reply, ok I will try to prepare shortly a zipped subset with the data and script I am using, so you can reproduce for debugging. Cheers, Gregor

**Comment by grexor** [comment] 2021-07-12 09:30
The R script and bam files here: https://www.expressrna.org/share/projects/20210525_ago2_rnaseq/AL/issue1.tar.gz

Thanks for all the help,
Gregor

**Comment by RJWANGbioinfo** [comment] 2021-07-18 03:07
Hi @grexor ,
Thanks for sharing your data. I just check the bam files, there are two issues:
1) In the pre-build PAS reference, the chromosomes are named with 'chr' prefix, while in your bam files, the chromosome names don't have this prefix. To make the PAS reference fit your bam, you need to add the following into your code:
```
seqlevelsStyle(UTRdbraw) = "NCBI"
dfIPA$Chrom = gsub('chr','',dfIPA$Chrom)
dfLE$Chrom = gsub('chr','',dfLE$Chrom)
```

2) No reads are mapped to the PAS region in your bam files:
```
apply(UTR_APA_OUT[,-1],2,max)
```
it reports all 0 in your bam files:
```
case14_GSM4194983_subset_areads      case14_GSM4194983_subset_aRPKM     case14_GSM4194983_subset_creads 
                                  0                                   0                                   0 
     case14_GSM4194983_subset_cRPKM    case14_GSM4194983_subset_3UTR_RE      case2_GSM4194982_subset_areads 
                                  0                                 NaN                                   0 
      case2_GSM4194982_subset_aRPKM      case2_GSM4194982_subset_creads       case2_GSM4194982_subset_cRPKM 
                                  0                                   0                                   0 
    case2_GSM4194982_subset_3UTR_RE      case3_GSM4194984_subset_areads       case3_GSM4194984_subset_aRPKM 
                                NaN                                   0                                   0 
     case3_GSM4194984_subset_creads       case3_GSM4194984_subset_cRPKM     case3_GSM4194984_subset_3UTR_RE 
                                  0                                   0                                 NaN 
  control1_GSM4194978_subset_areads    control1_GSM4194978_subset_aRPKM   control1_GSM4194978_subset_creads 
                                  0                                   0                                   0 
   control1_GSM4194978_subset_cRPKM  control1_GSM4194978_subset_3UTR_RE  control2_SRR10544953_subset_areads 
                                  0                                 NaN                                   0 
  control2_SRR10544953_subset_aRPKM  control2_SRR10544953_subset_creads   control2_SRR10544953_subset_cRPKM 
                                  0                                   0                                   0 
control2_SRR10544953_subset_3UTR_RE   control3_GSM4194980_subset_areads    control3_GSM4194980_subset_aRPKM 
                                NaN                                   0                                   0 
  control3_GSM4194980_subset_creads    control3_GSM4194980_subset_cRPKM  control3_GSM4194980_subset_3UTR_RE 
                                  0                                   0                                 NaN 
  control4_GSM4194981_subset_areads    control4_GSM4194981_subset_aRPKM   control4_GSM4194981_subset_creads 
                                  0                                   0                                   0 
   control4_GSM4194981_subset_cRPKM  control4_GSM4194981_subset_3UTR_RE   control5_GSM4194977_subset_areads 
                                  0                                 NaN                                   0 
   control5_GSM4194977_subset_aRPKM   control5_GSM4194977_subset_creads    control5_GSM4194977_subset_cRPKM 
                                  0                                   0                                   0 
 control5_GSM4194977_subset_3UTR_RE 
                                NaN 
```

You may want to check your raw data and bam files regarding this.

**Comment by grexor** [comment] 2021-07-18 10:01
Thanks so much for checking this out, will try to fix it, Cheers

**Comment by RJWANGbioinfo** [comment] 2021-07-25 04:07
Close this ticket since it's not the issue of the code in APAlyzer

**Closed as completed by RJWANGbioinfo** 2021-07-25 04:07 UTC

**Comment by vafadare** [comment] 2025-03-18 09:29
Hey there. I get the same error but the issue doesn't come from the fact that there are all zeros in the output file. If you interested to debug this, I can share my data here.

Thanks
